# Generated by Django 3.0.5 on 2020-04-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200428_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='tag',
        ),
    ]
